### ISSUE TITLE
[FEATURE] prisma to establish secure connection when sslkey and sslcert being provided

### ISSUE THREAD

**Issue by rfdc** [tylim88/Create-Prisma-App#4]
Hi @tylim88,

I'm trying to deploy on Google cloud platform. Their DB uses SSL connection.

Have you tried it before? 

I will let you know if there is any update on it. Perhaps we can add to this template ;) 

Thanks
Rafa

**Comment by rfdc** [comment]
I found this https://github.com/prisma/prisma/issues/3286

**Comment by tylim88** [comment]
Hello rfdc,

currently I have errands to run, but I will research and add this feature when I have time

as far as I can see, you can add a ssl flag in the docker compose file
```
        databases:
          default:
            connector: postgres
            host: postgres
            port: ${PSQL_PORT}
            user: ${PSQL_USER}
            password: ${PSQL_PASSWORD}
            migrations: true
            ssl:true
```
